#!/usr/bin/env python3
"""THE GUNSLINGER — asset generator.

Every diagram in this repository is generated by this file and then VERIFIED
AGAINST ITS OWN RULES before it is allowed to exist. The validator is not a
formality: in the parent project three assets failed on their first pass, and
each failure is now a permanent regression check here.

The rules, and the failure each one remembers:

  1. NOTHING MAY LEAVE THE CANVAS.        A hero image once silently cut off
     nine labels. Caught by comparing text coordinates to the canvas, never by
     looking at the picture.
  2. text-anchor ∈ {start, middle, end}.  Letter-spacing was once passed into
     the anchor slot, emitting invalid SVG that still rendered locally.
  3. NO BLUR, NO GLOW, NO SCANLINES.      Photosensitivity hazard, and they
     destroy the crisp edges contrast measurement depends on.
  4. TYPE NEVER DROPS BELOW 12px.         Anything smaller is decoration
     pretending to be information.
  5. TEXT SITS ON A SOLID SURFACE.        Contrast is only provable when the
     background is known.
  6. EVERY ASSET CARRIES title + desc.    A diagram a screen reader cannot
     announce is a diagram half the audience cannot read.
  7. ONE DATA SERIES IS ONE COLOUR.       Per-bar hues encode nothing the label
     does not already say.

A generator that cannot refuse is not a guard. This one was tested by feeding it
a deliberately broken diagram to confirm it says no.
"""
import json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAL  = {t["name"]: t["hex"] for t in
        json.load(open(os.path.join(ROOT, "assets/palettes/palette.json")))["tokens"]}

MONO = ("ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, "
        "'Liberation Mono', monospace")
MIN_TYPE = 12
ANCHORS  = {"start", "middle", "end"}
CHAR_W   = 0.62          # measured advance width for this monospace stack


class Canvas:
    def __init__(self, w, h, title, desc):
        self.w, self.h, self.title, self.desc = w, h, title, desc
        self.parts, self.texts = [], []
        self.parts.append('<rect width="%d" height="%d" fill="%s"/>' % (w, h, PAL["bg"]))

    # ---- primitives -------------------------------------------------------
    def card(self, x, y, w, h, fill="card", stroke="border", sw=1.5, rx=6):
        self.parts.append(
            '<rect x="%g" y="%g" width="%g" height="%g" rx="%g" fill="%s" '
            'stroke="%s" stroke-width="%g"/>' % (x, y, w, h, rx, PAL[fill], PAL[stroke], sw))

    def text(self, x, y, s, size=14, fill="text", weight=400, anchor="start", ls=0.0):
        assert anchor in ANCHORS, "invalid text-anchor %r" % anchor
        assert size >= MIN_TYPE, "type below floor: %g" % size
        self.texts.append((x, y, s, size, anchor, ls))
        self.parts.append(
            '<text x="%g" y="%g" font-family="%s" font-size="%g" font-weight="%s" '
            'fill="%s" text-anchor="%s" letter-spacing="%g">%s</text>'
            % (x, y, MONO, size, weight, PAL[fill], anchor, ls, _esc(s)))

    def rule(self, x1, y, x2, stroke="border", sw=1.5):
        self.parts.append('<line x1="%g" y1="%g" x2="%g" y2="%g" stroke="%s" '
                          'stroke-width="%g"/>' % (x1, y, x2, y, PAL[stroke], sw))

    def arrow(self, x1, y1, x2, y2, stroke="teal", sw=2.5):
        """Straight arrow with an explicit head drawn as line segments - no
        marker defs, so the head can never inherit an unknown fill."""
        self.parts.append('<line x1="%g" y1="%g" x2="%g" y2="%g" stroke="%s" '
                          'stroke-width="%g"/>' % (x1, y1, x2, y2, PAL[stroke], sw))
        if x1 == x2:                                    # vertical
            d = 1 if y2 > y1 else -1
            self.parts.append('<path d="M%g %g L%g %g L%g %g" fill="none" stroke="%s" '
                'stroke-width="%g" stroke-linecap="round"/>'
                % (x2-7, y2-9*d, x2, y2, x2+7, y2-9*d, PAL[stroke], sw))
        else:                                           # horizontal
            d = 1 if x2 > x1 else -1
            self.parts.append('<path d="M%g %g L%g %g L%g %g" fill="none" stroke="%s" '
                'stroke-width="%g" stroke-linecap="round"/>'
                % (x2-9*d, y2-7, x2, y2, x2-9*d, y2+7, PAL[stroke], sw))

    def line(self, x1, y1, x2, y2, stroke="teal", sw=2.5):
        """Connector with NO head. Use when another primitive supplies the head -
        an arrowhead mid-path reads as a terminus that is not one."""
        self.parts.append('<line x1="%g" y1="%g" x2="%g" y2="%g" stroke="%s" '
                          'stroke-width="%g"/>' % (x1, y1, x2, y2, PAL[stroke], sw))

    def diag(self, x1, y1, x2, y2, stroke="teal", sw=2.5):
        """Diagonal arrow with a head rotated to the actual path angle. The
        straight arrow() branches on vertical-vs-horizontal and would draw a
        horizontal head on a sloped line."""
        import math
        a = math.atan2(y2 - y1, x2 - x1)
        self.parts.append('<line x1="%g" y1="%g" x2="%g" y2="%g" stroke="%s" '
                          'stroke-width="%g"/>' % (x1, y1, x2, y2, PAL[stroke], sw))
        for off in (2.6, -2.6):
            hx = x2 + 12 * math.cos(a + off)
            hy = y2 + 12 * math.sin(a + off)
            self.parts.append('<line x1="%g" y1="%g" x2="%g" y2="%g" stroke="%s" '
                'stroke-width="%g" stroke-linecap="round"/>' % (x2, y2, hx, hy, PAL[stroke], sw))

    def elbow(self, x1, y1, x2, y2, stroke="teal", sw=2.5):
        """Down, across, then down again - for the branch diagrams."""
        my = (y1 + y2) / 2
        self.parts.append('<path d="M%g %g L%g %g L%g %g L%g %g" fill="none" '
            'stroke="%s" stroke-width="%g" stroke-linejoin="round"/>'
            % (x1, y1, x1, my, x2, my, x2, y2-10, PAL[stroke], sw))
        d = 1 if y2 > my else -1
        self.parts.append('<path d="M%g %g L%g %g L%g %g" fill="none" stroke="%s" '
            'stroke-width="%g" stroke-linecap="round"/>'
            % (x2-7, y2-9*d, x2, y2, x2+7, y2-9*d, PAL[stroke], sw))

    def badge(self, x, y, s, colour="teal", size=13):
        """Small pill. Width measured from the string, never guessed."""
        w = len(s) * size * CHAR_W + 20
        self.parts.append('<rect x="%g" y="%g" width="%g" height="%g" rx="10" '
            'fill="%s" stroke="%s" stroke-width="1.5"/>'
            % (x, y, w, size + 12, PAL["card2"], PAL[colour]))
        self.text(x + w/2, y + size + 4, s, size=size, fill=colour, weight=700,
                  anchor="middle", ls=1.2)
        return w

    def heading(self, s, sub):
        self.text(56, 70, s, size=36, weight=700, ls=3.0)
        self.text(56, 100, sub, size=16, fill="muted")
        self.rule(56, 122, self.w - 56)

    # ---- emit + validate --------------------------------------------------
    def svg(self):
        return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" '
                'width="%d" height="%d" role="img" aria-labelledby="t d">\n'
                '<title id="t">%s</title>\n<desc id="d">%s</desc>\n%s\n</svg>\n'
                % (self.w, self.h, self.w, self.h, _esc(self.title),
                   _esc(self.desc), "\n".join(self.parts)))

    def validate(self):
        errs = []
        s = self.svg()
        for pat, msg in ((r"filter\s*=", "filter attribute present"),
                         (r"feGaussianBlur", "blur filter present"),
                         (r"opacity\s*=\s*\"0?\.[0-4]", "text/shape below 0.5 opacity")):
            if re.search(pat, s):
                errs.append(msg)
        for a in set(re.findall(r'text-anchor="([^"]+)"', s)):
            if a not in ANCHORS:
                errs.append("invalid text-anchor: %s" % a)
        for sz in re.findall(r'font-size="([\d.]+)"', s):
            if float(sz) < MIN_TYPE:
                errs.append("type below %dpx: %s" % (MIN_TYPE, sz))
        # the one that actually caught a real bug: does any label leave the canvas?
        for (x, y, txt, size, anchor, ls) in self.texts:
            adv = len(txt) * (size * CHAR_W + ls)
            x0 = x if anchor == "start" else (x - adv/2 if anchor == "middle" else x - adv)
            x1 = x0 + adv
            if x0 < 0 or x1 > self.w or y < size or y > self.h:
                errs.append("OVERFLOW %r  x=[%.0f,%.0f] y=%.0f  canvas %dx%d"
                            % (txt[:38], x0, x1, y, self.w, self.h))
        if not self.parts or 'fill="%s"' % PAL["bg"] not in self.parts[0]:
            errs.append("missing solid background")
        return errs

    def write(self, name):
        errs = self.validate()
        if errs:
            print("  REFUSED %s" % name)
            for e in errs[:8]:
                print("     - %s" % e)
            return False
        p = os.path.join(ROOT, "assets/vectors/diagrams", name + ".svg")
        open(p, "w").write(self.svg())
        print("  wrote %-30s %dx%d  %d text nodes" % (name + ".svg", self.w, self.h,
                                                      len(self.texts)))
        return True


def _esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def rasterise():
    """PNG previews. SVG remains the deliverable.

    NOTE a real bug this function once had: it selected a tool by name from
    `which`, then dispatched on a DIFFERENT set of names, so it silently
    converted nothing and still reported a count. It now asserts that the
    number of PNGs written matches the number of SVGs found, and says so
    loudly when it does not - because "rasterised 0" printed cheerfully is
    exactly the class of lie this whole project exists to catch.
    """
    vd = os.path.join(ROOT, "assets/vectors/diagrams")
    ed = os.path.join(ROOT, "assets/exports")
    svgs = [f for f in sorted(os.listdir(vd)) if f.endswith(".svg")]
    conv = None
    if subprocess.run(["which", "rsvg-convert"], capture_output=True).returncode == 0:
        conv = lambda src, dst: subprocess.run(["rsvg-convert", "-o", dst, src], check=True)
    else:
        try:
            import cairosvg
            conv = lambda src, dst: cairosvg.svg2png(url=src, write_to=dst, scale=1.0)
        except ImportError:
            print("  no rasteriser available - SVG only")
            return
    made = 0
    for f in svgs:
        src, dst = os.path.join(vd, f), os.path.join(ed, f[:-4] + ".png")
        try:
            conv(src, dst)
            if os.path.exists(dst) and os.path.getsize(dst) > 0:
                made += 1
        except Exception as e:
            print("  RASTER FAILED %s: %s" % (f, e))
    if made != len(svgs):
        print("  RASTER INCOMPLETE: %d PNG for %d SVG" % (made, len(svgs)))
    else:
        print("  rasterised %d/%d PNG previews" % (made, len(svgs)))
